/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class stdutil */

#ifndef _Included_stdutil
#define _Included_stdutil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     stdutil
 * Method:    downloadfile
 * Signature: (Ljava/lang/String;ZLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_stdutil_downloadfile
  (JNIEnv *env, jobject, jstring url, jboolean filewrite, jstring outputPath);

/*
 * Class:     stdutil
 * Method:    frepy
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_stdutil_frepy
  (JNIEnv *env, jobject, jobject var1);

#ifdef __cplusplus
}
#endif
#endif
